FROM node:24-alpine AS build
WORKDIR /app
COPY WebUI/package*.json ./
RUN npm install
COPY WebUI/ .
RUN npm run build -- --configuration production

FROM nginx:stable-alpine
COPY WebUI/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/WebUI/browser /usr/share/nginx/html
EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD curl --fail http://localhost:80/healthz || exit 1

CMD ["nginx", "-g", "daemon off;"]