FROM node:22-alpine AS build
WORKDIR /app
COPY certstore-frontend/package*.json ./
RUN npm ci
COPY certstore-frontend/ .
RUN npm run build -- --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/certstore-frontend/browser /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80